config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "blog_posts#index"
  resources :blog_posts, only: [:index, :show, :new, :create, :update, :edit, :destroy]

  # Users Routes
  resources :users, only: [:new, :create, :edit, :update, :show, :destroy]

  # Sessions Routes
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    belongs_to :user, foreign_key: 'author_id'
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :username, presence: true, uniqueness: true
    validates :email, presence: true, uniqueness: true
    
    has_many :blog_posts, foreign_key: 'author_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  
  def current_user
      @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
    before_action :set_blog_post, only: [:show, :edit, :update, :destroy]
    before_action :check_admin, only: [:new, :create, :edit, :update, :destroy]

    def index
        @blog_posts = BlogPost.all.order(created_at: :desc)
    end

    def show
        @blog_post = BlogPost.find(params[:id])
        @can_edit = @current_user && (@current_user.admin? || current_user == @blog_post.user)
    end

    def new
        @blog_post = BlogPost.new
    end

    def create
        @blog_post = current_user.blog_posts.build(blog_post_params)
        if @blog_post.save
            redirect_to @blog_post, notice: 'Blog post was successfully created.'
        else
            render :new
        end
    end

    def edit
    end

    def update
        if @blog_post.update(blog_post_params)
            redirect_to @blog_post, notice: 'Blog post was successfully updated.'
        else
            render :edit
        end
    end
    
    def destroy
        if @blog_post.user == current_user || current_user&.admin?
          if @blog_post.destroy
            redirect_to root_path, notice: 'Blog post was successfully deleted.'
          else
            redirect_to @blog_post, alert: 'Failed to delete the blog post.'
          end
        else
          redirect_to root_path, alert: 'You are not authorized to delete this blog post.'
        end
      end

    private

    def set_blog_post
        @blog_post = BlogPost.find(params[:id])
    end
    
    def check_admin
        redirect_to root_path, alert: 'Access denied.' unless current_user&.admin?
    end
    
    def blog_post_params
        params.require(:blog_post).permit(:title, :body)
    end
    
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end

    def create
        @user = User.find_by(username: params[:username])
        if !!@user && @user.authenticate(params[:password])
            session[:user_id] = @user.id
            redirect_to root_path
        else
            message = "Something went wrong! Make sure your username and password are correct."
            redirect_to login_path, notice: message
        end
    end

    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "You have been logged out successfully."
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            flash[:notice] = "User created successfully"
            redirect_to root_path
        else
            flash[:alert] = "User not created"
            render :new, status: :unprocessable_entity
        end
    end

    def show
        @user = User.find(params[:id])
    end

    private

    def user_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    def logged_in?
        !!sesssion[:user_id]
    end

    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if !!session[:user_id]
    end
end

app/views/blog_posts/edit.html.erb
<h1>Edit Blog Post</h1>

<%= form_with(model: @blog_post, local: true) do |form| %>
  <% if @blog_post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog post from being saved:</h2>
      <ul>
        <% @blog_post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', blog_posts_path, class: 'btn btb-form' %>

app/views/blog_posts/index.html.erb
<head>
    <% content_for :title do %>
        HIBTB - Home
    <% end %>
</head>

<body>
    <div class='blog_index'>
        <% @blog_posts.each do |post| %>
            <h2><%= link_to post.title, blog_post_path(post), class: 'index_title' %></h2>
            <p><%= post.user.username + ' - ' + post.created_at.strftime("%B %d, %Y") %></p>
            <p><%= truncate(post.body, length: 150) %></p>
        <% end %>
    <div>
</body>

app/views/blog_posts/new.html.erb
<head>
    <% content_for :title do %>
        HIBTB - New Post
    <% end %>
</head>

<h1>New post</h1>

<%= form_with(model: @blog_post, local: true) do |form| %>
    <% if @blog_post.errors.any? %>
        <div id="error_explanation">
        <h2><%= pluralize(@blog_post.errors.count, "error") %> prohibited this blog post from being saved:</h2>
        <ul>
            <% @blog_post.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
        </ul>
        </div>
    <% end %>
    
    <div class="new_user_form">
        <div class="field">
            <%= form.label :title %>
            <%= form.text_field :title %>
        </div>

        <div class="field">
            <%= form.label :body %>
            <%= form.text_area :body %>
        </div>

        <div class="actions">
            <%= form.submit %>
        </div>
    </div>
<% end %>

<%= link_to 'Back', blog_posts_path %>

app/views/blog_posts/show.html.erb
<head>
    <% content_for :title do %>
        HIBTB - <%= @blog_post.title %>
    <% end %>
</head>

<body>
    <h1><%= @blog_post.title %></h1>
    <h3><%= ('- ' + @blog_post.user.username) %></h3>
    <small><%= @blog_post.created_at.strftime("%B %d, %Y") %></small>
    <div><%= simple_format(@blog_post.body) %></div>
    <%= link_to "Back to All Posts", blog_posts_path %>

    <% if current_user&.admin? %>
        <%= link_to 'Edit', edit_blog_post_path(@blog_post) %>
        <%= link_to 'Delete', blog_post_path(@blog_post), 
                    data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' } %>
    <% end %>

    <% if current_user&.admin? %>
        <%= link_to 'New Blog Post', new_blog_post_path %>
    <% end %>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title).presence || "HIBTB" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <script data-goatcounter="https://myrolorin.goatcounter.com/count"
        async src="//gc.zgo.at/count.js"></script>

    <div class="header">
      <h1>How I Built This Blog</h1>
      <h3>Ramblings from an ADHD dad learning dev</h3>
    </div>
    <div class="nav">
      <%= link_to "Home", root_path %>
      <% if current_user %>
        <%= link_to current_user.username, user_path(current_user) %>
        <%= link_to "Log Out", logout_path, method: :delete %>
      <% else %>
        <%= link_to "Log In", login_path %>
        <%= link_to "Sign Up", new_user_path %>
      <% end %>
    </div>
  </head>

  <body>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<head>
    <% content_for :title do %>
        HIBTB - Sign Up
    <% end %>
</head>

<h1>New user</h1>

<%= form_with model: @user do |f| %>
    <% if @user.errors.any? %>
        <div>
            <% @user.errors.full_messages.each do |message| %>
                <%= message %><br>
            <% end %>
        </div>
    <% end %>
    <br>
    <div>
        <%= f.label :username %><br>
        <%= f.text_field :username %>
    </div>
    <div>
        <%= f.label :email %><br>
        <%= f.text_field :email %>
    <div>
        <%= f.label :password %><br>
        <%= f.password_field :password %>
    </div>
    <div>
        <%= f.label :password_confirmation %><br>
        <%= f.password_field :password_confirmation %>
    </div>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/users/show.html.erb
<head>
    <% content_for :title do %>
        HIBTB - <%= @user.username %>
    <% end %>
</head>

<h1>This is in progress</h1>
Username: <%= current_user.username %><br>
Email: <%= current_user.email %>